### ISSUE TITLE
Using the command file

### ISSUE THREAD

**Issue by ArekStrojec** [dynarithmic/twainsave#2]
Dear Dynarithmic Support Team,

I would like to ask if using a configuration file with a list of parameters is supported in this version. If it is, could you please provide the syntax for the file and the switch to invoke the application with this file?

Best regards,
Arek

**Comment by dynarithmic** [comment]
The **--@** syntax should be supported in this version, for example **twainsave-opensource --@ yourconfigfile.txt**.   

The syntax of file is described [here](https://www.dynarithmic.com/onlinehelp/twainsave/_.htm)

**Comment by ArekStrojec** [comment]
I am trying to apply the application below

twainsave-opensource.exe --@ config.txt

file config.txt
-resolution 300
-color 2

The application does not start

but
the application starts if the config file is empty

**Comment by ArekStrojec** [comment]
The application works properly

Thank you for your support.

Best regards,
Arek
