### ISSUE TITLE
Problem with --filename option ?

### ISSUE THREAD

**Issue by ArekStrojec** [dynarithmic/twainsave#3]
Dear Dynarithmic Support Team,

The application documentation allows saving the created scan to a file containing spaces. 

Unfortunately, when performing the scan as below
twainsave-opensource.exe --filename  "FileName with Spaces.pdf" --filetype pdf

I receive a file with an incorrect name: "FileName"

I tested on the 32 bit version.

Please provide support.

Best regards,
Arek

**Comment by dynarithmic** [comment]
Please test with the latest version from the master-staging repo.

**Comment by ArekStrojec** [comment]
I downloaded new version 

Problem has been solved

thank you for your support
